### ISSUE TITLE
About the paper "Generalized Domain Conditioned Adaptation Network" (TPAMI-2020-06-0743)

### ISSUE THREAD

**Issue by hello-trouble** [BIT-DA/GDCAN#1]
Thank you very much for your excellent job. So sorry to bother you.  However, I can't find this paper from the internet,  Can you share this excellent paper "Generalized Domain Conditioned Adaptation Network" (TPAMI-2020-06-0743)。

**Comment by BinhuiXie** [comment]
Hi, I am sorry that this work is still under peer review.

**Comment by BinhuiXie** [comment]
Our article has been published in the Early Access area on IEEE Xplore. https://ieeexplore.ieee.org/document/9366353

**Comment by lixinghpu** [comment]
Congratulations and Thank you again. It is very excellent.
