### ISSUE TITLE
About the channel attention

### ISSUE THREAD

**Issue by hello-trouble** [BIT-DA/GDCAN#4]
![image](https://user-images.githubusercontent.com/33440801/114671355-95aefc80-9d36-11eb-8836-bad472aca027.png)
Thank you for your excellent job about the condition domain. I am very insteresed in  the novel channel attetion. In this project, images of source domain and target domain are concated. If images of different domains are feed into different parts of the FC layers separatively, does it still work?  Is there any difference?  Thank you in advance for your kind help.

**Comment by BinhuiXie** [comment]
Hi @hello-trouble, as shown below, it is true that we seperate source and target images and feed them into different paths of the FC layers in implementation.
source path:
https://github.com/BIT-DA/GDCAN/blob/89af3139bfb523398f111df6b1183ab306d5a67a/DCAN/network.py#L62
target path:
https://github.com/BIT-DA/GDCAN/blob/89af3139bfb523398f111df6b1183ab306d5a67a/DCAN/network.py#L64

**Comment by hello-trouble** [comment]
Thank you very much for your reply. It's excellent.
